import type { ChapterSummary, ExtensionIndex, ExtensionStatus, FloorspecIndex, LibraryIndex, SpecIndex } from './ast';
import indexData from './generated/index.json';
import lock from './floorspec.lock.json';

/**
 * What the site knows about the Floorspec drafts it publishes, without any chapter's content
 * (DI-T-10.2, DI-T-10.4, DI-T-10.5, DI-T-10.6, DI-T-10.7). Plain data — the routes, the Worker and the sitemap read it, so it must
 * stay small and free of React. Generated by `npm run sync:floorspec`; never edited by hand.
 */

/** The current draft of every specification with chapters at the pinned commit — Core, Ops, then Rules — in the order shown. */
export const SPECS: SpecIndex[] = (indexData as FloorspecIndex).specifications;

/** Every earlier draft still published, each from the commit that pinned it: Core and Ops 0.3, 0.2 and 0.1, Rules 0.1. */
export const EARLIER: SpecIndex[] = (indexData as FloorspecIndex).earlier;

/** Every extension in the registry at the pinned commit: /floorspec/registry/<name>. */
export const EXTENSIONS: ExtensionIndex[] = (indexData as FloorspecIndex).extensions;

/** Every library published at /floorspec/library/<name>/<version>/. */
export const LIBRARIES: LibraryIndex[] = (indexData as FloorspecIndex).libraries;

export const extensionByName = (name: string): ExtensionIndex | undefined => EXTENSIONS.find((ext) => ext.name === name);
export const libraryByName = (name: string): LibraryIndex | undefined => LIBRARIES.find((lib) => lib.name === name);

/** "Release Candidate": a registry status as the registry's README writes it. */
export const STATUS_LABEL: Record<ExtensionStatus, string> = {
  proposal: 'Proposal',
  draft: 'Draft',
  releaseCandidate: 'Release Candidate',
  ratified: 'Ratified',
};

/** A specification's current draft. */
export const specByCode = (code: string): SpecIndex | undefined => SPECS.find((spec) => spec.spec === code);

/** One draft of a specification, current or earlier. */
export const specAt = (code: string, version: string): SpecIndex | undefined =>
  [...SPECS, ...EARLIER].find((spec) => spec.spec === code && spec.version === version);

/** The earlier drafts of a specification, newest first. */
export const earlierOf = (code: string): SpecIndex[] => EARLIER.filter((spec) => spec.spec === code);

/** Whether this is the current draft of its specification. */
export const isCurrent = (spec: SpecIndex) => SPECS.includes(spec);

/** Floorspec Core: the document, and the specification every other one builds on. */
export const CORE: SpecIndex = specByCode('core')!;

export const FLOORSPEC_LOCK: {
  repository: string;
  commit: string;
  committedAt: string;
  /** Each specification's current draft version at that commit: `{ core: "0.4", ops: "0.4", rules: "0.2" }`. */
  specifications: Record<string, string>;
  /** Earlier drafts still published, and the commit each is published from: `{ core: { "0.1": { commit, committedAt } } }`. */
  earlier: Record<string, Record<string, { commit: string; committedAt: string }>>;
} = lock;

export const FLOORSPEC_REPO = `https://github.com/${FLOORSPEC_LOCK.repository}`;
/** A pinned commit's tree on GitHub (the current pin by default), optionally at a path inside it. */
export const pinnedTree = (path = '', commit = FLOORSPEC_LOCK.commit) => `${FLOORSPEC_REPO}/tree/${commit}${path ? `/${path}` : ''}`;
export const SHORT_SHA = FLOORSPEC_LOCK.commit.slice(0, 7);

export const chapterBySlug = (spec: SpecIndex, slug: string): ChapterSummary | undefined =>
  spec.chapters.find((chapter) => chapter.slug === slug);

/** `/floorspec/ops/references`, or `/floorspec/ops/0.1/references` for an earlier draft, optionally at an anchor. */
export const chapterPath = (spec: SpecIndex, slug: string, hash?: string) => `${spec.base}/${slug}${hash ? `#${hash}` : ''}`;

/** "5. Walls", "Annex A. IFC4 mapping". */
export const chapterLabel = (chapter: ChapterSummary) =>
  /^\d+$/.test(chapter.number) ? `${chapter.number}. ${chapter.title}` : `Annex ${chapter.number}. ${chapter.title}`;

/** "Floorspec Core 0.4". */
export const specName = (spec: SpecIndex) => `${spec.name} ${spec.version}`;

/**
 * The standard as the header names it, with the star colour it shares with D3 Floorspec. It is
 * not a project in PROJECTS — a standard is neither a tool nor a fix — but its pages carry its
 * mark the way a product's do.
 */
export const FLOORSPEC = {
  slug: 'floorspec',
  name: 'Floorspec',
  // d3-allow: Floorspec's own brand colour (chartreuse, DI-T-10.1), used only as its decorative mark — identity, not interface colour.
  accent: '#B5D84A',
};
