import type { ChapterSummary, FloorspecIndex, SpecIndex } from './ast';
import indexData from './generated/index.json';
import lock from './floorspec.lock.json';

/**
 * What the site knows about the Floorspec drafts it publishes, without any chapter's content
 * (DI-T-10.2, DI-T-10.4). Plain data — the routes, the Worker and the sitemap read it, so it must
 * stay small and free of React. Generated by `npm run sync:floorspec`; never edited by hand.
 */

/** Every specification with chapters at the pinned commit — Core, then Ops — in the order shown. */
export const SPECS: SpecIndex[] = (indexData as FloorspecIndex).specifications;

export const specByCode = (code: string): SpecIndex | undefined => SPECS.find((spec) => spec.spec === code);

/** Floorspec Core: the document, and the specification every other one builds on. */
export const CORE: SpecIndex = specByCode('core')!;

export const FLOORSPEC_LOCK: {
  repository: string;
  commit: string;
  committedAt: string;
  /** Each specification's draft version at that commit: `{ core: "0.1", ops: "0.1" }`. */
  specifications: Record<string, string>;
} = lock;

export const FLOORSPEC_REPO = `https://github.com/${FLOORSPEC_LOCK.repository}`;
/** The pinned commit's tree on GitHub, optionally at a path inside it. */
export const pinnedTree = (path = '') => `${FLOORSPEC_REPO}/tree/${FLOORSPEC_LOCK.commit}${path ? `/${path}` : ''}`;
export const SHORT_SHA = FLOORSPEC_LOCK.commit.slice(0, 7);

export const chapterBySlug = (spec: SpecIndex, slug: string): ChapterSummary | undefined =>
  spec.chapters.find((chapter) => chapter.slug === slug);

/** `/floorspec/ops/references`, optionally at an anchor. */
export const chapterPath = (spec: SpecIndex, slug: string, hash?: string) =>
  `/floorspec/${spec.spec}/${slug}${hash ? `#${hash}` : ''}`;

/** "5. Walls", "Annex A. IFC4 mapping". */
export const chapterLabel = (chapter: ChapterSummary) =>
  /^\d+$/.test(chapter.number) ? `${chapter.number}. ${chapter.title}` : `Annex ${chapter.number}. ${chapter.title}`;

/** "Floorspec Core 0.1". */
export const specName = (spec: SpecIndex) => `${spec.name} ${spec.version}`;

/**
 * The standard as the header names it, with the star colour it shares with D3 Floorspec. It is
 * not a project in PROJECTS — a standard is neither a tool nor a fix — but its pages carry its
 * mark the way a product's do.
 */
export const FLOORSPEC = {
  slug: 'floorspec',
  name: 'Floorspec',
  // d3-allow: Floorspec's own brand colour (chartreuse, DI-T-10.1), used only as its decorative mark — identity, not interface colour.
  accent: '#B5D84A',
};
