/**
 * The declarations scripts/sync-playground.ts writes beside the bundle: the part of D3 Floorspec's
 * API the playground uses, written out by hand. The packages' own .d.ts files import their
 * siblings and the generated schema types, and cannot be shipped alone; the sync refuses when a name
 * declared here is not exported by the bundle, or the other way round. Narrower than the packages'
 * own types where the playground needs less (a document's members are left open).
 */

const HEADER = `// Generated by scripts/sync-playground.ts from scripts/playground-dts.ts — never edit by hand.
// The surface of D3 Floorspec at the commit in lock.json that the /floorspec/playground uses.
`;

export const ENGINE_DTS = `${HEADER}
// @floorspec/engine

export type Severity = 'error' | 'warning' | 'info';

export interface DiagnosticLocation {
  /** A JSON Pointer (RFC 6901) into the document. */
  pointer?: string;
  level?: string;
  point?: [number, number];
}

/** A diagnostic (Core 10.2): its message's wording is not normative. */
export interface Diagnostic {
  code: string;
  severity: Severity;
  message: string;
  /** The elements involved, sorted. */
  elements: string[];
  location: DiagnosticLocation;
  fix?: unknown[];
  /** The option whose design it was found in (Core 19.5.2). */
  design?: string;
}

export type Tier = 'configuration' | 'parse' | 'document' | 'schema' | 'invariant' | 'lint';

/** One row of the diagnostic catalogue (Core 10.4). */
export interface CatalogueEntry {
  readonly code: string;
  readonly severity: Severity;
  readonly tier: Tier;
  readonly condition: string;
  readonly elements: string;
  readonly rule: string;
}

export declare const CATALOGUE: readonly CatalogueEntry[];

/** A Floorspec document. The playground reads only what it draws, so its members are left open. */
export interface FloorspecDocument {
  readonly floorspec: string;
  readonly [member: string]: unknown;
}

/** What the engine derives from a valid document; the playground only hands it to the mesher. */
export interface Derived {
  readonly [member: string]: unknown;
}

/** The files of a document's package (Core 18.4), by path relative to the document. */
export declare class Package {
  constructor(files: ReadonlyMap<string, Uint8Array> | Readonly<Record<string, Uint8Array>>);
  file(path: string): Uint8Array | undefined;
  get paths(): string[];
}

export interface ValidateOptions {
  readonly extensions?: readonly string[];
  readonly knownExtensions?: string | Uint8Array | readonly unknown[];
  readonly core?: '0.1' | '0.2' | '0.3';
  readonly design?: unknown;
  readonly package?: Package;
}

export interface Evaluation {
  /** True iff no diagnostic has severity error (Core 10.1.1). */
  valid: boolean;
  /** Every diagnostic, sorted by code and then by elements (Core 10.2). */
  diagnostics: Diagnostic[];
  /** The parsed document, when it parsed. */
  value?: unknown;
  /** The document, when it passed the schema tier. */
  document?: FloorspecDocument;
  /** Level geometry, when the reference invariants held. */
  analysis?: unknown;
  /** The document as seen in the derived design: the document itself without design options. */
  view?: FloorspecDocument;
}

export declare function evaluate(input: string | Uint8Array | object, options?: ValidateOptions): Evaluation;
/** Throws for an invalid document, or one whose design is not derived. */
export declare function deriveEvaluation(ev: Evaluation): Derived;
/** The canonical form (Core 9.2) of a valid document, ending in one line feed. */
export declare function canonicalize(doc: unknown): string;
/** The content hash (Core 9.3), in hex. */
export declare function contentHash(doc: unknown): string;
export declare function sha256(data: Uint8Array): Uint8Array;
export declare function toHex(bytes: Uint8Array): string;

/** The reader the reference implementation runs everywhere: every official extension, known at its version. */
export declare const OFFICIAL_READER: { readonly extensions: readonly string[]; readonly knownExtensions: readonly unknown[] };
export declare const ENGINE_VERSION: string;
export declare const CORE_VERSION: string;
export declare const IMPLEMENTED_VERSIONS: readonly string[];

// @floorspec/render2d

export interface RenderOptions {
  readonly level?: string;
  readonly design?: Readonly<Record<string, string>>;
  readonly theme?: 'light' | 'dark';
  /** SVG pixels per foot. Default 24. */
  readonly scale?: number;
  /** Element IDs drawn in the accent. */
  readonly highlight?: readonly string[];
  readonly dimensions?: boolean;
  readonly labels?: boolean;
  readonly clearances?: boolean;
  readonly roof?: boolean;
}

/** One level of a valid document as a standalone SVG. Throws for a document a core reader finds invalid. */
export declare function renderPlan(document: string | Uint8Array | object, options?: RenderOptions): string;
/** The level a plan shows when none is named: the lowest by elevation, then by ID. */
export declare function defaultLevel(doc: FloorspecDocument): string | undefined;

// @floorspec/package

export type PackageErrorCode =
  | 'not-a-zip'
  | 'corrupt'
  | 'zip64'
  | 'multi-disk'
  | 'encrypted'
  | 'unsupported-method'
  | 'unsafe-path'
  | 'symlink'
  | 'special-file'
  | 'duplicate-path'
  | 'too-large'
  | 'too-many-entries'
  | 'no-document'
  | 'conflict';

/** Why a file could not be read as a package: a code to branch on, a message a person can act on. */
export declare class PackageError extends Error {
  readonly code: PackageErrorCode;
  constructor(code: PackageErrorCode, message: string);
}

export interface PackagedAsset {
  readonly asset: string;
  readonly path: string;
  readonly sha256: string;
  readonly mediaType: string | null;
  readonly byteLength: number | null;
}

export interface OpenedPackage {
  /** Where the document was found, from the archive's root. */
  readonly documentPath: string;
  /** The document's bytes, exactly as packaged. */
  readonly document: Uint8Array;
  /** The files the document's assets name, by path relative to the document. */
  readonly files: Map<string, Uint8Array>;
  /** Assets whose file the package does not hold. */
  readonly missing: PackagedAsset[];
  /** Files nothing in the document names. */
  readonly ignored: string[];
}

/** Open a .floorspec archive, under the package's default limits. Throws PackageError. */
export declare function readPackage(zip: Uint8Array): OpenedPackage;
export declare function isZip(bytes: Uint8Array): boolean;
/** The document's name in a package: model.json. */
export declare const DOCUMENT_NAME: string;
`;

export const MESH_DTS = `${HEADER}
// @floorspec/mesh

import type { Derived, FloorspecDocument } from './engine.js';

export type Vec3 = [number, number, number];

export type PartKind =
  | 'wall'
  | 'junctionFill'
  | 'opening'
  | 'floor'
  | 'ceiling'
  | 'slab'
  | 'roof'
  | 'roofGable'
  | 'stairFlight'
  | 'stairLanding'
  | 'stairBlock'
  | 'extension';

/** An indexed triangle mesh in metres, relative to the result's origin, counter-clockwise seen from outside. */
export interface PartMesh {
  positions: Float32Array;
  indices: Uint32Array;
}

export interface MeshPart {
  key: string;
  /** The Floorspec element this part belongs to. */
  id: string;
  kind: PartKind;
  level: string;
  closed: boolean;
  facing?: 'up' | 'down' | 'side';
  placeholder?: true;
  material?: string;
  layers?: (string | null)[];
  opening?: { category: 'door' | 'window' | 'empty'; fill?: string; wall: string };
  extension?: { name: string; collection: string };
  mesh: PartMesh;
  /** In base units (1/1280 mm). */
  bbox: { min: Vec3; max: Vec3 };
}

export interface HouseMesh {
  unitsPerMetre: number;
  /** Subtracted from every position before it was converted to metres, in base units. */
  origin: Vec3;
  parts: MeshPart[];
  bbox: { min: Vec3; max: Vec3 } | null;
}

export interface MeshOptions {
  readonly include?: readonly PartKind[];
  readonly levels?: readonly string[];
  /** In base units. */
  readonly origin?: Vec3;
}

export interface Mesher {
  /** Mesh what the engine already derived from a valid document (its view, for one with design options). */
  meshDerived(doc: FloorspecDocument, derived: Derived, options?: MeshOptions): HouseMesh;
}

/** Load manifold-3d's WASM (once) and return a mesher whose calls are synchronous. */
export declare function loadMesher(options?: { locateFile?: () => string }): Promise<Mesher>;
/** An unindexed copy of a part's mesh with one normal per triangle, for crisp faces. */
export declare function flatShaded(mesh: PartMesh): { positions: Float32Array; normals: Float32Array };
`;
